// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYOr4kziwJVTDDfo1jhRUdZfA0JeUU4js',
    appId: '1:973188247715:web:9529f675d4e8d80f04cf16',
    messagingSenderId: '973188247715',
    projectId: 'genone-c0ddb',
    authDomain: 'genone-c0ddb.firebaseapp.com',
    storageBucket: 'genone-c0ddb.appspot.com',
    measurementId: 'G-9CM9QQQFL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOi7BQGD32xcrb9nIeah1QKgimIEvZkKw',
    appId: '1:973188247715:android:8418f63d42f1340604cf16',
    messagingSenderId: '973188247715',
    projectId: 'genone-c0ddb',
    storageBucket: 'genone-c0ddb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Cq5IPLDU9k7_hI_48jqkE-sDPiLg3lo',
    appId: '1:973188247715:ios:cc0188afba30fb3504cf16',
    messagingSenderId: '973188247715',
    projectId: 'genone-c0ddb',
    storageBucket: 'genone-c0ddb.appspot.com',
    iosClientId: '973188247715-ks5i1glc854mksqail34hn9jveu8pej9.apps.googleusercontent.com',
    iosBundleId: 'com.example.genoneWebFlutter',
  );
}
